### ISSUE TITLE
PHOTOMAP - Legend print checks

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/tdipisa#57]
I attached print screen from print output (pdf), where the text for layer (legend) is not show in full. would it be possible to wrap it into more lines.
![20190304_legend_wrapping.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5943f6b8abdc49001a6611c9/125516c66e82c728ace21e0d46bac4cb7ad2d0f9dbd6b346a358fe90165135723914aa2577c7af6aaf50740b0a0c0abe4b4a5a15f4fadf2da5e76f258c0a0eb9d16d5d22926b15f9bfd30da313f871d51bdaebe5c01982fa3737e68c854e3b1b041e80f95d32a79b48ca4abb.png)

**Comment by mbarto** [comment]
@tdipisa, can you give me the GeoServer / MapStore2 urls, so that I can do some testing?
