### ISSUE TITLE
CLEVEMETRO: Schedule installation pyfulcrum

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/tdipisa#71]
You can access the machine at 198.30.211.81
username:geosolutions

password:JosiOUeRLITi

Please change password and switch to using a key for authentication upon accessing the machine. Please also notify me when you have done so.

Also, we began configuring this machine per the directions previously, so nginx and other dependencies are already installed.

**Comment by simboss** [comment]
@tdipisa you can use @randomorder for the basic things like ssh and so on but maybe someone else for doing the full thing.

You can talk to Giovanni but then we can decide on Thu.
